### ISSUE TITLE
Actions compilation fails - Download iOS SDK dependency

### ISSUE THREAD

**Issue by cybrnook** [dayanch96/YTMusicUltimate#273]
### Describe the bug

```yaml
Compilation fails on step “Download iOS SDK”.

Run git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
fatal: could not read Username for 'https://github.com': Device not configured
Error: Process completed with exit code 128.

Assume it’s because arichorns account has issues at the moment. Perhaps there is an alternate source?
```

### Steps to reproduce

```yaml
Compile using actions
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [x] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by oldman20** [comment]
i have same issue
And please update tweak patches, it was work on YTMusic 7.07.2 patches 2.1, But not work on YTMusic newer (cant play in background)

**Comment by wkefriowehfjewhf** [comment]
It's due to the original SDK repo from arichorn no longer being accessible, just change it to use arichornloverALT's SDK instead and it will work. [Like this.](https://github.com/dayanch96/YTMusicUltimate/pull/274/commits/f0f6edca81ef9f06f9d4670a3c5364bacf6cc9f2)

**Comment by cybrnook** [comment]
Proposed PR fix: https://github.com/dayanch96/YTMusicUltimate/pull/274

**Comment by oldman20** [comment]
> It's due to the original SDK repo from arichorn no longer being accessible, just change it to use arichornloverALT's SDK instead and it will work. [Like this.](https://github.com/dayanch96/YTMusicUltimate/pull/274/commits/f0f6edca81ef9f06f9d4670a3c5364bacf6cc9f2)
> 
> Also background playback works fine for me on the latest version (7.10) so idk about that.

Thank, i tried and now it work on 7.10.2. btw when installing with TrollStore, has popup:
![photo_2024-07-18_12-19-47](https://github.com/user-attachments/assets/d86fb77a-b4fa-42fe-b78a-defa28f79f8d)
Is it normally? Cause i remember it not when use 7.07.2?

**Comment by chwhaanews** [comment]
![Screenshot_2024-07-19-12-17-33-767_com.github.android-edit.jpg](https://github.com/user-attachments/assets/6683b2bc-e52e-40e2-b993-e2c3b3faf8ba)

it works

**Comment by hetzjagd** [comment]
The linked answers and threads above 404 for me but I am having the same issue.  I am trying to patch youtube music decrypted .ipa 7.10

**Comment by TheStealDeal** [comment]
@oldman20 I've tried with the ALT but it does not work

**Comment by oldman20** [comment]
@TheStealDeal , @hetzjagd It work for me:
![image](https://github.com/user-attachments/assets/6ab06bee-492f-41af-8ce8-a60176149c6f)

**Comment by i-matveev** [comment]
@TheStealDeal , @hetzjagd
Take a close look at what is updated in the code. Everything works.

```
          cache-name: iOS-16.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
```
