### ISSUE TITLE
Crash Issues

### ISSUE THREAD

**Issue by QDH-ENGINE** [dayanch96/YTMusicUltimate#340]
### Describe the bug

```yaml
Crash issue happens when i press "ytmusicultimate". 
Jailbroken with : dopamine 2.0 roothide latest ver
Installed from : ginsu repo. (Since im using roothide, i converted via patcher)
Device details : iOS 16.6 beta 1 iPhone 13 Pro
```

### Steps to reproduce

```yaml
1. Go to app
2. Press my account's profile
3. Press YTMusicUltimate
4. Crashes
```

### Crashlog

[Crashed.txt](https://github.com/user-attachments/files/20612283/Crashed.txt)

### Post Requisites

- [x] I have checked that a similar issue has not been reported before.
- [x] Verified the relevance of the project and the version you are using.
- [x] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [x] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**
